[project]
name = "ontorag-mcp"
version = "0.1.0"
description = "OntoRAG MCP Server for Ontologies"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.129.0",
    "fastmcp>=2.14.5",
    "rdflib>=7.6.0",
]
